//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinder.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int ID { get; set; }
        public int Activity_Id { get; set; }
        public System.DateTime DateZan { get; set; }
        public Nullable<int> Mark_Id { get; set; }
        public int Group_Id { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Group Group { get; set; }
        public virtual Mark Mark { get; set; }
    }
}
